sudo: required
dist: trusty

os:
- osx
- linux

env:
- NODE_ENV=prod

language: node_js

node_js:
- '8'

cache:
  yarn: true
  directories:
  - node_modules
  - app/node_modules
  - $HOME/.electron
  - $HOME/.cache

addons:
  apt:
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - g++-4.8

script:
  - yarn

before_deploy:
- export TOKEN="$GITHUB_AUTH_TOKEN" OWNER="MaidSafe" REPO="release_config"
- export FILE="https://api.github.com/repos/$OWNER/$REPO/contents/safe_authenticator/log.toml"
- curl -O "$FILE" -H "Authorization:token $TOKEN" -H "Accept:application/vnd.github.v3.raw"
- yarn package
- yarn post-package
- export WEB_HOSTING_MANAGER="$(ls release/*.zip)";
- export SHA_256_SUM_WHM="$(ls release/*.txt)";
- echo "${WEB_HOSTING_MANAGER}, ${SHA_256_SUM_WHM} being deployed."

deploy:
  provider: releases
  skip_cleanup: true
  api_key: $GITHUB_AUTH_TOKEN
  file: 
    - "${WEB_HOSTING_MANAGER}"
    - "${SHA_256_SUM_WHM}"
  draft: true
  prerelease: true
  tag_name: $TRAVIS_TAG
  on:
    tags: true
